[project]
name = 'hiro-hacks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.bootstrap]
path = 'contracts/proposals/bootstrap.clar'
clarity_version = 2
epoch = 2.4

[contracts.grants-vault]
path = 'contracts/extensions/grants-vault.clar'
clarity_version = 2
epoch = 2.4

[contracts.core]
path = 'contracts/core.clar'
clarity_version = 2
epoch = 2.4

[contracts.extension-trait]
path = 'contracts/traits/extension-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.membership-token]
path = 'contracts/extensions/membership-token.clar'
clarity_version = 2
epoch = 2.4

[contracts.milestone-disbursement]
path = 'contracts/extensions/milestone-disbursement.clar'
clarity_version = 2
epoch = 2.4

[contracts.proposal-submission]
path = 'contracts/extensions/proposal-submission.clar'
clarity_version = 2
epoch = 2.4

[contracts.proposal-trait]
path = 'contracts/traits/proposal-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.proposal-voting]
path = 'contracts/extensions/proposal-voting.clar'
clarity_version = 2
epoch = 2.4

[contracts.test-grant]
path = 'contracts/test_proposals/test-grant.clar'
clarity_version = 2
epoch = 2.4

[contracts.vault]
path = 'contracts/extensions/vault.clar'
clarity_version = 2
epoch = 2.4

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
